/* ═══════════════════════════════════════════════════════════
   PhiloTask — Philosopher/Saint Data & Quotes Database
   ═══════════════════════════════════════════════════════════ */

const PHILOSOPHERS = [
  { id: 'socrates',        name: 'Socrates',            cardName: 'Socrates',      image: 'images/socrates.png',        origin: 'Greek',     color: '#4fc3f7', initials: 'SO', isSaint: false },
  { id: 'aristotle',       name: 'Aristotle',           cardName: 'Aristotle',     image: 'images/aristotle.png',       origin: 'Greek',     color: '#81c784', initials: 'AR', isSaint: false },
  { id: 'marcus_aurelius', name: 'Marcus Aurelius',     cardName: 'M. Aurelius',   image: 'images/marcus_aurelius.png', origin: 'Roman',     color: '#e57373', initials: 'MA', isSaint: false },
  { id: 'sun_tzu',         name: 'Sun Tzu',             cardName: 'Sun Tzu',       image: 'images/sun_tzu.png',         origin: 'Chinese',   color: '#ffb74d', initials: 'ST', isSaint: false },
  { id: 'confucius',       name: 'Confucius',           cardName: 'Confucius',     image: 'images/confucius.png',       origin: 'Chinese',   color: '#f06292', initials: 'CO', isSaint: false },
  { id: 'pascal',          name: 'Blaise Pascal',       cardName: 'B. Pascal',     image: 'images/pascal.png',          origin: 'French',    color: '#ba68c8', initials: 'BP', isSaint: false },
  { id: 'seneca',          name: 'Seneca',              cardName: 'Seneca',        image: 'images/seneca.jpg',          origin: 'Roman',     color: '#4db6ac', initials: 'SE', isSaint: false },
  { id: 'epictetus',       name: 'Epictetus',           cardName: 'Epictetus',     image: 'images/epictetus.png',       origin: 'Greek',     color: '#aed581', initials: 'EP', isSaint: false },
  { id: 'laozi',           name: 'Lao Tzu',             cardName: 'Lao Tzu',       image: 'images/laozi.jpg',           origin: 'Chinese',   color: '#9575cd', initials: 'LT', isSaint: false },
  { id: 'plato',           name: 'Plato',               cardName: 'Plato',         image: 'images/plato.jpg',           origin: 'Greek',     color: '#64b5f6', initials: 'PL', isSaint: false },
  { id: 'chrysostom',      name: 'St. John Chrysostom', cardName: 'Chrysostom',    image: 'images/chrysostom.jpg',      origin: 'Christian', color: '#ffd54f', initials: 'JC', isSaint: true },
  { id: 'basil',           name: 'St. Basil the Great', cardName: 'St. Basil',     image: 'images/basil.jpg',           origin: 'Christian', color: '#a5d6a7', initials: 'SB', isSaint: true },
  { id: 'paul',            name: 'St. Paul',            cardName: 'St. Paul',      image: 'images/paul.jpg',            origin: 'Christian', color: '#ef9a9a', initials: 'SP', isSaint: true },
  { id: 'jesus',           name: 'Jesus Christ',        cardName: 'Jesus Christ',  image: 'images/jesus.jpg',           origin: 'Christian', color: '#ffe082', initials: 'IC', isSaint: true },
];

const QUOTES = {
  welcome: [
    { text: 'The unexamined life is not worth living.', author: 'socrates', source: 'Apology, 38a' },
    { text: 'Knowing yourself is the beginning of all wisdom.', author: 'aristotle', source: 'Nicomachean Ethics, Book X' },
    { text: 'When you arise in the morning, think of what a precious privilege it is to be alive — to breathe, to think, to enjoy, to love.', author: 'marcus_aurelius', source: 'Meditations, Book II.1' },
    { text: 'A journey of a thousand miles begins with a single step.', author: 'laozi', source: 'Tao Te Ching, Ch. 64' },
    { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'confucius', source: 'The Analects, Book XIII' },
    { text: 'All of humanity\'s problems stem from man\'s inability to sit quietly in a room alone.', author: 'pascal', source: 'Pensées, §139' },
    { text: 'We suffer more in imagination than in reality.', author: 'seneca', source: 'Letters to Lucilius, Letter 13' },
    { text: 'It is not what happens to you, but how you react to it that matters.', author: 'epictetus', source: 'Discourses, Book I.1' },
    { text: 'The measure of a man is what he does with power.', author: 'plato', source: 'The Republic, Book I' },
    { text: 'Be kind, for everyone you meet is fighting a hard battle.', author: 'plato', source: 'Protagoras, 313a (attributed)' },
    { text: 'The soul takes nothing with her to the next world but her education and culture.', author: 'plato', source: 'Phaedo, 107d' },
    { text: 'Come to me, all you who are weary and burdened, and I will give you rest.', author: 'jesus', source: 'Matthew 11:28' },
    { text: 'I am the light of the world. Whoever follows me will not walk in darkness.', author: 'jesus', source: 'John 8:12' },
    { text: 'I can do all things through Christ who strengthens me.', author: 'paul', source: 'Philippians 4:13' },
    { text: 'Let no one despise your youth, but be an example to the believers in word, in conduct, in love.', author: 'paul', source: '1 Timothy 4:12' },
    { text: 'Would you become a pillar of the Church? Lean first upon Christ.', author: 'chrysostom', source: 'Homilies on Ephesians, Homily 11' },
    { text: 'A tree is known by its fruit; a man by his deeds. A good deed is never lost.', author: 'basil', source: 'Homily on Humility' },
    { text: 'The Lord is my shepherd; I shall not want.', author: 'jesus', source: 'Psalm 23:1 (quoted by Jesus)' },
    { text: 'Dwell on the beauty of life. Watch the stars, and see yourself running with them.', author: 'marcus_aurelius', source: 'Meditations, Book VII.47' },
    { text: 'True knowledge exists in knowing that you know nothing.', author: 'socrates', source: 'Apology (reported by Plato), 21d' },
    { text: 'Do not conform to the pattern of this world, but be transformed by the renewing of your mind.', author: 'paul', source: 'Romans 12:2' },
    { text: 'Glory to God in the highest, and on earth peace to those on whom his favour rests.', author: 'jesus', source: 'Luke 2:14' },
    { text: 'No act of kindness, no matter how small, is ever wasted.', author: 'chrysostom', source: 'Homilies on the Gospel of Matthew, Homily 15' },
    { text: 'The beginning of the way to virtue is the recognition that we are capable of it.', author: 'basil', source: 'Address to Young Men, Ch. 2' },
    { text: 'Man is the most intelligent of the animals — and the most silly.', author: 'diogenes', source: 'Diogenes Laërtius, Lives, Book VI' },
    { text: 'In the midst of winter, I found there was within me an invincible summer.', author: 'seneca', source: 'Letters to Lucilius, Letter 23' },
  ],
  taskCreated: [
    { text: 'Well begun is half done.', author: 'aristotle', source: 'Politics, Book V.4' },
    { text: 'Let him who would move the world first move himself.', author: 'socrates', source: 'Attributed, via Plutarch' },
    { text: 'Begin at once to live, and count each separate day as a separate life.', author: 'seneca', source: 'Letters to Lucilius, Letter 101' },
    { text: 'Opportunities multiply as they are seized.', author: 'sun_tzu', source: 'The Art of War, Ch. 5' },
    { text: 'You have power over your mind — not outside events. Realize this, and you will find strength.', author: 'marcus_aurelius', source: 'Meditations, Book VI.8' },
    { text: 'The heart has its reasons which reason knows nothing of.', author: 'pascal', source: 'Pensées, §277' },
    { text: 'A thousand-mile journey begins beneath one\'s feet.', author: 'laozi', source: 'Tao Te Ching, Ch. 64' },
    { text: 'First say to yourself what you would be; then do what you have to do.', author: 'epictetus', source: 'Discourses, Book III.23' },
    { text: 'The secret of getting ahead is getting started.', author: 'confucius', source: 'The Analects, Book XV' },
    { text: 'He who is not courageous enough to take risks will accomplish nothing in life.', author: 'confucius', source: 'The Analects, Book XVII' },
    { text: 'Every new beginning comes from some other beginning\'s end.', author: 'seneca', source: 'Letters to Lucilius, Letter 2' },
    { text: 'Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.', author: 'jesus', source: 'Matthew 6:34' },
    { text: 'For God has not given us a spirit of fear, but of power and of love and of a sound mind.', author: 'paul', source: '2 Timothy 1:7' },
    { text: 'The impediment to action advances action. What stands in the way becomes the way.', author: 'marcus_aurelius', source: 'Meditations, Book V.20' },
    { text: 'Attack is the secret of defense; defense is the planning of an attack.', author: 'sun_tzu', source: 'The Art of War, Ch. 6' },
    { text: 'If you want to lift yourself up, lift up someone else.', author: 'basil', source: 'Homily on Charity, §3' },
    { text: 'Do not wait for leaders; do it alone, person to person.', author: 'chrysostom', source: 'Homilies on the Acts of the Apostles, Homily 20' },
    { text: 'He who knows when he can fight and when he cannot will be victorious.', author: 'sun_tzu', source: 'The Art of War, Ch. 3' },
    { text: 'Knowing is not enough; we must apply. Wishing is not enough; we must do.', author: 'aristotle', source: 'Nicomachean Ethics, Book II.4' },
    { text: 'Delay not; swift is the flight of fortune\'s greatest favours.', author: 'seneca', source: 'De Brevitate Vitae, Ch. 9' },
    { text: 'Seize the day, and put the least possible trust in tomorrow.', author: 'seneca', source: 'De Brevitate Vitae, Ch. 3' },
    { text: 'Be strong and courageous. Do not be afraid; do not be discouraged.', author: 'jesus', source: 'Joshua 1:9 (spoken to Joshua)' },
    { text: 'Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.', author: 'paul', source: 'Colossians 3:23' },
    { text: 'Let us not become weary in doing good, for at the proper time we will reap a harvest.', author: 'paul', source: 'Galatians 6:9' },
    { text: 'He who has a why to live can bear almost any how.', author: 'epictetus', source: 'Discourses, Book I.6 (paraphrase)' },
    { text: 'Nothing in the world is as soft and yielding as water. Yet for dissolving the hard and inflexible, nothing can surpass it.', author: 'laozi', source: 'Tao Te Ching, Ch. 78' },
    { text: 'The richness of the mind is the only true wealth.', author: 'chrysostom', source: 'Homilies on the Gospel of John, Homily 32' },
    { text: 'Acquire the habit of attending carefully to what is said by another, and of entering, as far as possible, into the mind of the speaker.', author: 'marcus_aurelius', source: 'Meditations, Book VI.53' },
  ],
  taskCompleted: [
    { text: 'Excellence is the result of high intention, sincere effort, and intelligent execution.', author: 'aristotle', source: 'Nicomachean Ethics, Book II.1' },
    { text: 'Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.', author: 'sun_tzu', source: 'The Art of War, Ch. 4' },
    { text: 'Our greatest glory is not in never falling, but in rising every time we fall.', author: 'confucius', source: 'The Analects, Book XIV' },
    { text: 'True happiness is to enjoy the present, without anxious dependence upon the future.', author: 'seneca', source: 'De Vita Beata, Ch. 5' },
    { text: 'He who conquers himself is the mightiest warrior.', author: 'confucius', source: 'The Analects, Book XIV.32' },
    { text: 'Waste no more time arguing about what a good man should be. Be one.', author: 'marcus_aurelius', source: 'Meditations, Book X.16' },
    { text: 'Nature does not hurry, yet everything is accomplished.', author: 'laozi', source: 'Tao Te Ching, Ch. 17' },
    { text: 'Man\'s greatness lies in his power of thought.', author: 'pascal', source: 'Pensées, §346' },
    { text: 'No man is free who is not master of himself.', author: 'epictetus', source: 'Discourses, Book IV.1' },
    { text: 'The only true wisdom is in knowing you know nothing.', author: 'socrates', source: 'Apology, 21d (Plato)' },
    { text: 'Pleasure in the job puts perfection in the work.', author: 'aristotle', source: 'Nicomachean Ethics, Book X.4' },
    { text: 'The happiness of your life depends upon the quality of your thoughts.', author: 'marcus_aurelius', source: 'Meditations, Book V.16' },
    { text: 'When the archer misses the mark, he turns round and seeks for the cause within himself.', author: 'confucius', source: 'Doctrine of the Mean, Ch. 14' },
    { text: 'Wealth consists not in having great possessions, but in having few wants.', author: 'epictetus', source: 'Discourses, Book III.24' },
    { text: 'Knowing others is intelligence; knowing yourself is true wisdom.', author: 'laozi', source: 'Tao Te Ching, Ch. 33' },
    { text: 'Supreme excellence consists in breaking the enemy\'s resistance without fighting.', author: 'sun_tzu', source: 'The Art of War, Ch. 3' },
    { text: 'Well done, good and faithful servant; you have been faithful over a little, I will set you over much.', author: 'jesus', source: 'Matthew 25:21' },
    { text: 'I have fought the good fight, I have finished the race, I have kept the faith.', author: 'paul', source: '2 Timothy 4:7' },
    { text: 'The reward of a thing well done is to have done it.', author: 'seneca', source: 'Letters to Lucilius, Letter 81' },
    { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'aristotle', source: 'Nicomachean Ethics, Book II (paraphrased by Durant)' },
    { text: 'He who is brave is free.', author: 'seneca', source: 'Letters to Lucilius, Letter 85' },
    { text: 'Silence is a source of great strength.', author: 'laozi', source: 'Tao Te Ching, Ch. 23' },
    { text: 'Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character.', author: 'chrysostom', source: 'Homilies on the Epistle to the Hebrews, Homily 28' },
    { text: 'Strive for progress, not perfection, for God sees the heart.', author: 'basil', source: 'Longer Rules, Q. 2' },
    { text: 'Do not let your left hand know what your right hand is doing.', author: 'jesus', source: 'Matthew 6:3' },
    { text: 'I press on toward the goal to win the prize for which God has called me heavenward.', author: 'paul', source: 'Philippians 3:14' },
    { text: 'The one who endures to the end will be saved.', author: 'jesus', source: 'Matthew 24:13' },
    { text: 'This is the day the Lord has made; let us rejoice and be glad in it.', author: 'jesus', source: 'Psalm 118:24 (quoted by Christ)' },
    { text: 'What does it profit a man to gain the whole world, yet forfeit his soul?', author: 'jesus', source: 'Mark 8:36' },
    { text: 'May the God of hope fill you with all joy and peace as you trust in him.', author: 'paul', source: 'Romans 15:13' },
    { text: 'Let all that you do be done in love.', author: 'paul', source: '1 Corinthians 16:14' },
    { text: 'He who does not make the effort will not taste the honey.', author: 'chrysostom', source: 'Homilies on the Gospel of Matthew, Homily 43' },
    { text: 'Nothing is more powerful than gentleness in one who is truly great.', author: 'basil', source: 'Letter 2, To Gregory of Nazianzus' },
    { text: 'Do not say a little in many words, but a great deal in a few.', author: 'plato', source: 'Protagoras, 329b' },
    { text: 'The beginning is the most important part of the work.', author: 'plato', source: 'The Republic, Book II' },
  ],
};
